### ISSUE TITLE
solandra: sorting doesn't work after documents are in cache

### ISSUE THREAD

**Issue by ghost** [tjake/Solandra#13] opened 2010-04-29 21:55 UTC
The first time you do a given search with a sort order, it works correctly. If you run the same search immediately after this (while the docs are in cache), the results are out of order.

**Comment by tjake** [comment] 2010-04-30 01:52
I'm not able to reproduce this. is this happening with solr? or with lucene directly?
the solrconfig.xml in example should do no caching.

**Comment by ghost** [comment] 2010-04-30 03:30
OK. It was with solr but not with the example. I will check my solrconfig.xml (pretty much copied from a vanilla solr setup) against the one in the example and see what I can figure out.

**Comment by ghost** [comment] 2010-04-30 15:25
I am definitely able to repeat this using the solr example and the standard request handler. 

Using a clean copy of the source tree, after setting up the solr example as per the README file
1. Setup Cassandra 0.6 with storage-conf.xml in config
2. ant lucandra.jar
3. cd solr-example; java -jar start.jar
4. cd exampledocs; ./post.sh *.xml

Run this query
http://localhost:8983/solr/select/?q=ipod&version=2.2&start=0&rows=10&indent=on&sort=price%20desc&fl=id,name,price&wt=json

The first time I run it, the sort order will be correct. Now run it again and the sort order changes.

Kill and restart solr. 

Run this query (using the dismax request handler)
http://localhost:8983/solr/select/?q=ipod&version=2.2&start=0&rows=10&indent=on&sort=price%20desc&fl=id,name,price&wt=json&qt=dismax

Now the sort order is correct and remains stable when I refresh / re-run the search.

**Comment by tjake** [comment] 2010-05-05 02:42
Looks like solr is still caching sorts. I need to replace the default QueryComponent with my own

**Comment by tjake** [comment] 2010-11-02 17:47
fixed by issue 37

**Closed as completed by tjake** 2010-11-02 17:47 UTC
