### ISSUE TITLE
Quote search terms can cause search failure

### ISSUE THREAD

**Issue by rob7hunter** [tjake/Solandra#17] opened 2010-05-18 23:11 UTC
Searching for a multi-word phrase in double quotes yields a null. Below I've modified the bookmarks demo to show you how to reproduce the error. On my machine (Mac, Snow Leopard) with the newest Lucandra (from today), I see A and B print, but not C. I think an error is being swallowed up, as at the very end I get a "null" printed. Note that if I change the phrase to <code>"\"hello world\""</code> or something else that doesn't appear in a document, everything goes fine--"C" is printed, and I see "Search matched: 0 item(s)" at the end.

```
    QueryParser qp = new QueryParser(Version.LUCENE_CURRENT, "title", analyzer);
System.out.println("A");
    Query q = qp.parse("\"set up\"");
    System.out.println("B");
    TopDocs docs = indexSearcher.search(q, 10);
    System.out.println("C");
    ...
```

**Comment by tjake** [comment] 2010-05-20 01:29
I think this was just caused by the bookmark using the wrong analyzer. I checked in a fix, can you try again?

**Comment by rob7hunter** [comment] 2010-05-20 16:42
The issue remains, but I've forked and checked in a unit test which reproduces the issue. See

http://github.com/vegashacker/Lucandra/commit/24a38696f72f183fb3441a74ccc910110152db7d

When you run the test, you get a NPE:
    [junit] java.lang.NullPointerException
    [junit]     at lucandra.LucandraTermDocs.nextPosition(LucandraTermDocs.java:184)
    [junit]     at org.apache.lucene.search.PhrasePositions.nextPosition(PhrasePositions.java:76)
    [junit]     at org.apache.lucene.search.PhrasePositions.firstPosition(PhrasePositions.java:65)
    [junit]     at org.apache.lucene.search.ExactPhraseScorer.phraseFreq(ExactPhraseScorer.java:34)
    [junit]     at org.apache.lucene.search.PhraseScorer.doNext(PhraseScorer.java:105)
    [junit]     at org.apache.lucene.search.PhraseScorer.nextDoc(PhraseScorer.java:89)
    [junit]     at org.apache.lucene.search.Scorer.score(Scorer.java:74)
    [junit]     at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:248)
    [junit]     at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:173)
    [junit]     at org.apache.lucene.search.Searcher.search(Searcher.java:181)
    [junit]     at org.apache.lucene.search.Searcher.search(Searcher.java:191)
    [junit]     at lucandra.LucandraTests.testSimpleAnalyzerWriteRead(LucandraTests.java:361)

**Comment by tjake** [comment] 2010-05-21 01:02
Thanks for the example. I was able to fix it now.

**Comment by tjake** [comment] 2010-05-27 01:26
closed

**Closed as completed by tjake** 2010-05-27 01:26 UTC
